### ISSUE TITLE
Widget Crashed

### ISSUE THREAD

**Issue by HonestAbe7** [adolfintel/Clock31#1]
Thank you for your effort in making a clock and calendar widget. Unfortunately, the widget crashed when I tried to place it on my screen. I am using Android 10. Looking forward to your next version release. Thanks

**Comment by adolfintel** [comment]
Can you provide some more info? What phone and rom are you using? Does it crash before or after asking for calendar permission?

**Comment by adolfintel** [comment]
Alright, I'll change that code and release an update in the next few days

**Comment by adolfintel** [comment]
I just commited a change to the widget creation code, here's a test APK in case you don't have Android Studio installed: 
[app-release.zip](https://github.com/adolfintel/Clock31/files/10006066/app-release.zip)

Let me know if it works.

**Comment by HonestAbe7** [comment]
Thanks but the updated file still crashes on my phone.

**Comment by adolfintel** [comment]
Do you have Android Studio installed so we can check logcat?

**Comment by HonestAbe7** [comment]
No I don't. Do I need to download it and if so where?

**Comment by adolfintel** [comment]
First, remove Clock31 from Settings > Apps.

You can get Android Studio here: https://developer.android.com/studio/
Once installed, download this repo, open it in Android Studio, connect your phone with USB debugging enabled and you should see logcat at the bottom.

Example:
![image](https://user-images.githubusercontent.com/16307689/201741101-19c039d6-805d-438f-a823-00341a153afd.png)

**Comment by moriel5** [comment]
@adolfintel No changes here either.

I generally use a rooted phone (with a custom ROM), however since I have not yet had the time to do here, when I have time on my desktop, I'll get the log output via ADB (I do not believe that I need Android Studio for this, and I am comfortable with with the command line to do this, especially since I run Linux).

**Comment by HonestAbe7** [comment]
I am using an LG phone with Android 10. It does grant access to the calendar but I have Google calendar disabled and no calendar installed. Would that make a difference?

**Comment by adolfintel** [comment]
Added a couple of checks in case there are no clock/calendar apps installed.
Test APK: 
[app-release.zip](https://github.com/adolfintel/Clock31/files/10009554/app-release.zip)

**Comment by moriel5** [comment]
@adolfintel Sorry I want able to check anything earlier as I had fallen asleep (it was towards the end of the night, and I was taking care of chores).

That last APK works as it should, after an initial crash the first time, when it asks for the Calendar permission.

Perhaps it is because I had disabled (via ADB) almost all of the Google apps on there (when replacing the ROM, I generally also run GAPPS-less), sans a few like GBoard, that don't need the Play Services to function and I haven't yet manage to get a suitable replacement (FlorisBoard is coming along, however it is not yet ready, in my opinion).

I should be able to get logs pertaining that initial crash within the hour, so that is what I'll do.

**Comment by adolfintel** [comment]
Thanks, looking forward to seeing that log.
I use a rom without google services too so I can definitely exclude it as the issue.

**Comment by moriel5** [comment]
@adolfintel Yeah, sorry about not being clear, I had meant that because as part of those apps, I had also disabled Google Calendar, which means that there is no Calendar app enabled (technically, there should have also not been a clock app, however I needed to easily check the time in multiple timezones in order to know when is a good time to contact people I have ordered items from and/or make an international call, so I installed one that is based upon the AOSP clock from is GitHub source (the is a newer version on F-Droid)).

**Comment by HonestAbe7** [comment]
Thanks for the update. It works just fine now. Any way to resize the date without it taking up the whole screen? What about changing colors? Thanks

**Comment by moriel5** [comment]
@adolfintel I'm sorry about the delay and lack of notification. In the end I didn't have the time to take the logs earlier, and with each delay I thought that I would be able to within a few minutes.

Here are the logs (I tried to clean them up a little by removing unnecessary lines that do not not pertain to Clock31): 
[Clock31 Log](https://github.com/adolfintel/Clock31/files/10024965/Clock31.Log)

Interestingly, the crashes have completely disappeared, with only a few milliseconds of delay during the initial placement of the widget.

**Comment by adolfintel** [comment]
Thanks for the log.
There doesn't seem to be anything unusual in it, so I guess the couple of extra checks in the initialization process fixed the crashing.

I'll push an update soon
